export const MOVIMIENTO = {
  INGRESO: 'INGRESO',
  EGRESO: 'EGRESO',
} as const;

export const BANCO = {
  BCP: 'BCP',
  BBVA: 'BBVA',
  INTERBANK: 'INTERBANK',
  SCOTIABANK: 'SCOTIABANK',
  YAPE: 'YAPE',
  PLIN: 'PLIN',
  EFECTIVO: 'EFECTIVO',
  OTROS: 'OTROS',
} as const;

export const TIPO_TRANSACCION = {
  PAGO_QR: 'PAGO QR',
  YAPEO_CELULAR: 'YAPEO CELULAR',
  PAGO_SERVICIO: 'PAGO SERVICIO',
  TRANSFERENCIA: 'TRANSFERENCIA',
  EFECTIVO: 'EFECTIVO',
  COMPRA: 'COMPRA',
  VENTA: 'VENTA',
  OTROS: 'OTROS',
} as const;

export const CATEGORIA = {
  VIVIENDA: 'Vivienda',
  ALIMENTACION: 'Alimentación',
  TRANSPORTE: 'Transporte',
  SALUD: 'Salud',
  SERVICIOS: 'Servicios',
  ENTRETENIMIENTO: 'Entretenimiento',
  EDUCACION: 'Educación',
  PERSONAL: 'Personal',
  OTROS: 'Otros',
} as const;

export const TIPOS_EGRESO = [
  TIPO_TRANSACCION.PAGO_QR,
  TIPO_TRANSACCION.YAPEO_CELULAR,
  TIPO_TRANSACCION.PAGO_SERVICIO,
  TIPO_TRANSACCION.TRANSFERENCIA,
  TIPO_TRANSACCION.COMPRA,
  TIPO_TRANSACCION.EFECTIVO
];

export const ALERTAS = {
  ADVERTENCIA: 'ADVERTENCIA (80%)',
  LIMITE_ALCANZADO: 'LIMITE ALCANZADO (100%)',
} as const;
